[project]
name = "resource-wise-backend"
version = "0.1.0"
description = "FastAPI backend for Resource Wise"
authors = [
    {name = "Jatin Gandhi",email = "jatin.gandhi@kickdrumtech.com"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.3,<0.35.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
