"""initial setup

Revision ID: 27900207ff35
Revises: 
Create Date: 2025-06-12 17:51:35.433089

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27900207ff35'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_is_deleted'), table_name='allocations')
    op.drop_column('allocations', 'is_deleted')
    op.drop_index(op.f('ix_designations_is_deleted'), table_name='designations')
    op.drop_column('designations', 'is_deleted')
    op.add_column('employee_embeddings', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('employee_embeddings', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('employee_embeddings', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_employee_embeddings_is_deleted'), table_name='employee_embeddings')
    op.create_index(op.f('ix_employee_embeddings_created_by'), 'employee_embeddings', ['created_by'], unique=False)
    op.create_index(op.f('ix_employee_embeddings_deleted_by'), 'employee_embeddings', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_employee_embeddings_updated_by'), 'employee_embeddings', ['updated_by'], unique=False)
    op.create_foreign_key(None, 'employee_embeddings', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'employee_embeddings', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'employee_embeddings', 'users', ['deleted_by'], ['id'])
    op.drop_column('employee_embeddings', 'is_deleted')
    op.drop_index(op.f('ix_employee_skills_is_deleted'), table_name='employee_skills')
    op.drop_column('employee_skills', 'is_deleted')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_column('employees', 'is_deleted')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_column('projects', 'is_deleted')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.add_column('projects', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.add_column('employees', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.add_column('employee_skills', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_employee_skills_is_deleted'), 'employee_skills', ['is_deleted'], unique=False)
    op.add_column('employee_embeddings', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'employee_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'employee_embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_employee_embeddings_updated_by'), table_name='employee_embeddings')
    op.drop_index(op.f('ix_employee_embeddings_deleted_by'), table_name='employee_embeddings')
    op.drop_index(op.f('ix_employee_embeddings_created_by'), table_name='employee_embeddings')
    op.create_index(op.f('ix_employee_embeddings_is_deleted'), 'employee_embeddings', ['is_deleted'], unique=False)
    op.drop_column('employee_embeddings', 'deleted_by')
    op.drop_column('employee_embeddings', 'updated_by')
    op.drop_column('employee_embeddings', 'created_by')
    op.add_column('designations', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_designations_is_deleted'), 'designations', ['is_deleted'], unique=False)
    op.add_column('allocations', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_allocations_is_deleted'), 'allocations', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
